export const Dummy = [{
    id: 1,
    name: "Hand Bag",
    price: "$100",
    image: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image1: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image2: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image3: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image4: "", 
    info: "An elegant evening clutch for special occasions.",
    description:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    category: "Fashion",
    rating: 4.5,
    stock: 50,
    location: "New York"

},

{
    id: 2,
    name: "Leather Wallet",
    price: "$50",
    image: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image1: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image2: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image3: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
    image4: "https://alabamart.com/cdn/shop/products/636b76820c4d1.jpg?v=1670834857&width=53",
    info: "An elegant evening clutch for special occasions.",
    description:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    category: "Accessories",
    rating: 4.7,
    stock: 30,
    location: "New York"
},
{
    id: 3,
    name: "Canvas Tote Bag",
    price: "$25",
    image: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image1: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image2: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image3: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
    image4: "",
    info: "An elegant evening clutch for special occasions.",
    description:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    category: "Bags",
    rating: 4.2,
    stock: 100,
    location: "New York"
},
{
    id: 4,
    name: "Stylish Backpack",
    price: "$75",
    image: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image1: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image2: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image3: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
    image4: "",
    info: "An elegant evening clutch for special occasions.",
    description:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    category: "Bags",
    rating: 4.6,
    stock: 20,
    location: "New York"
},
{
    id: 5,
    name: "Evening Clutch",
    price: "$80",
   image: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image1: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image2: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image3: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
    image4: "",
    info: "An elegant evening clutch for special occasions.",
    description:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    category: "Fashion",
    rating: 4.8,
    stock: 15,
    location: "New York"
},
{
    id: 6,
    name: "Travel Duffel Bag",
    price: "$120",
    image: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image1: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image2: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image3: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
    image4: "",
    info: "An elegant evening clutch for special occasions.",
    description:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    category: "Bags",
    rating: 4.9,
    stock: 10,
    location: "New York"
},
{
    id: 7,
    name: "Iphone",
    price: "$60",
    image: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image1: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image2: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image3: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
    image4: "",
    info: "An elegant evening clutch for special occasions.",
    description:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    category: "Electronics",
    rating: 4.3,
    stock: 40,
    location: "New York"
},

{
    id: 8,
    name: "Smart Tv",
    price: "$100",
    image: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image1: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image2: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image3: "https://oneandko.com/wp-content/uploads/2018/03/straight-human-hair-plus-closure.png",
        image4: "",
    info: "An elegant evening clutch for special occasions.",
    description:"lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    category: "Fashion",
    rating: 4.5,
    stock: 50,
    location: "New York"

},] 